In [ ]:
from google.colab import drive
drive.mount("drive")

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).

In [ ]:
import pandas as pd
import os# to list something like directory like doc,files# to list from a directory
from skimage.transform import resize#to resize images so that all images will be in same size
from skimage.io import imread# to read image
import numpy as np

In [ ]:
os.listdir("/content/drive/MyDrive/Data")

['Dog', 'Cat']

In [ ]:
imread("/content/drive/MyDrive/Data/Cat/cat.18.jpg")

array([[[110,   0,  14],
        [115,   3,  19],
        [119,   7,  23],
        ...,
        [112,   5,  33],
        [112,   5,  33],
        [112,   5,  33]],

       [[110,   0,  14],
        [114,   2,  18],
        [116,   4,  20],
        ...,
        [116,   9,  37],
        [116,   9,  37],
        [116,   9,  37]],

       [[116,   4,  18],
        [117,   5,  19],
        [119,   4,  19],
        ...,
        [116,   9,  37],
        [116,   9,  37],
        [116,   9,  37]],

       ...,

       [[167,  13,  25],
        [169,  15,  27],
        [172,  16,  29],
        ...,
        [169,   9,  21],
        [168,   8,  20],
        [168,   8,  20]],

       [[160,  10,  21],
        [163,  11,  23],
        [167,  13,  25],
        ...,
        [167,   7,  19],
        [167,   7,  19],
        [168,   8,  20]],

       [[155,   8,  18],
        [159,   9,  20],
        [162,  10,  22],
        ...,
        [165,   5,  17],
        [166,   6,  18],
        [167,   7,  19]]], dtype=uint8)

In [ ]:
os.listdir("/content/drive/MyDrive/Data/Cat")

['cat.18.jpg',
 'cat.30.jpg',
 'cat.13.jpg',
 'cat.42.jpg',
 'cat.27.jpg',
 'cat.32.jpg',
 'cat.36.jpg',
 'cat.3 - Copy.jpg',
 'download6.jpeg',
 'cat.46.jpg',
 'cat.28.jpg',
 'cat.9.jpg',
 'cat.51.jpg',
 'cat.5 - Copy.jpg',
 'cat.31.jpg',
 'cat.20.jpg',
 'download2.jpeg',
 'cat.41.jpg',
 'cat.53.jpg',
 'cat.50.jpg',
 'cat.5.jpg',
 'download3.jpeg',
 'cat.48.jpg',
 'cat.17.jpg',
 'downloadcat.jpeg',
 'cat.34.jpg',
 'cat.2 - Copy.jpg',
 'cat.37.jpg',
 'download1.jpeg',
 'cat.35.jpg',
 'download.jpeg',
 'cat.47.jpg',
 'cat.49.jpg',
 'images.jpeg',
 'cat.7.jpg',
 'cat.40.jpg',
 'cat.8.jpg',
 'download5.jpeg',
 'cat.44.jpg',
 'cat.39.jpg',
 'download4.jpeg',
 'cat.52.jpg',
 'cat.4 - Copy.jpg',
 'download7.jpeg',
 'download8.jpeg',
 'images9.jpeg',
 'cat.54.jpg',
 'cat.29.jpg',
 'cat.43.jpg',
 'cat.16.jpg',
 'cat.11.jpg',
 'cat.10.jpg',
 'cat.24.jpg',
 'cat.14.jpg',
 'cat.21.jpg',
 'cat.38.jpg',
 'cat.1 - Copy.jpg',
 'cat.12.jpg',
 'cat.15.jpg',
 'cat.33.jpg']

In [ ]:
len(os.listdir("/content/drive/MyDrive/Data/Dog"))# to find the length of the file dog

66

In [ ]:
len(os.listdir("/content/drive/MyDrive/Data/Cat"))

60

In [ ]:
catpath=os.path.join("/content/drive/MyDrive/Data","Cat")# join-it is used to join 2 paths like cat and data
for img in os.listdir(catpath):# to display all images in cat
  print(img)

cat.18.jpg
cat.30.jpg
cat.13.jpg
cat.42.jpg
cat.27.jpg
cat.32.jpg
cat.36.jpg
cat.3 - Copy.jpg
download6.jpeg
cat.46.jpg
cat.28.jpg
cat.9.jpg
cat.51.jpg
cat.5 - Copy.jpg
cat.31.jpg
cat.20.jpg
download2.jpeg
cat.41.jpg
cat.53.jpg
cat.50.jpg
cat.5.jpg
download3.jpeg
cat.48.jpg
cat.17.jpg
downloadcat.jpeg
cat.34.jpg
cat.2 - Copy.jpg
cat.37.jpg
download1.jpeg
cat.35.jpg
download.jpeg
cat.47.jpg
cat.49.jpg
images.jpeg
cat.7.jpg
cat.40.jpg
cat.8.jpg
download5.jpeg
cat.44.jpg
cat.39.jpg
download4.jpeg
cat.52.jpg
cat.4 - Copy.jpg
download7.jpeg
download8.jpeg
images9.jpeg
cat.54.jpg
cat.29.jpg
cat.43.jpg
cat.16.jpg
cat.11.jpg
cat.10.jpg
cat.24.jpg
cat.14.jpg
cat.21.jpg
cat.38.jpg
cat.1 - Copy.jpg
cat.12.jpg
cat.15.jpg
cat.33.jpg

In [ ]:
# to convert this into numerical.we save it as in array
flat_data_arr=[] #used to store features.to convert it into nu
target_arr=[]# this is to select if it is dog or cat ie to label if it is cat or dog
categories=["Cat","Dog"]# cat -0, dog-1

In [ ]:
data_dir=("/content/drive/MyDrive/Data")
for i in categories:
  print("loading ...category",i)
  path=os.path.join(data_dir,i)# to join 2 paths 1st part is datapath+catpath .here we get path of cat
  for img in os.listdir(path):
    img_array=imread(os.path.join(path,img))# to read an an image
    img_resized=resize(img_array,(150,150,3))# to resize image,here we get 3d
    flat_data_arr.append(img_resized.flatten())#flatten is used to convert 3d,2d to 1d
    target_arr.append(categories.index(i))# cat-0,dog-1
  print('loaded',i)

loading ...category Cat
loaded Cat
loading ...category Dog
loaded Dog

In [ ]:
#jst creating dataframe
#intially we had 126 values but using flatten we get 6750
df=pd.DataFrame(flat_data_arr)
df

,0,1,2,3,4,5,6,7,8,9,...,67490,67491,67492,67493,67494,67495,67496,67497,67498,67499
0,0.450773,0.011956,0.071498,0.450767,0.006846,0.059286,0.471130,0.015850,0.064732,0.474026,...,0.062624,0.642030,0.015206,0.069585,0.646300,0.015762,0.079527,0.654410,0.026855,0.074540
1,0.266514,0.270436,0.278279,0.281895,0.285817,0.293660,0.320151,0.324072,0.331915,0.285575,...,0.802532,0.701904,0.736721,0.795792,0.687784,0.732520,0.788196,0.676392,0.726043,0.779649
2,0.364724,0.310068,0.119902,0.385498,0.332242,0.135228,0.405248,0.354222,0.147759,0.422624,...,0.344426,0.400584,0.412349,0.337839,0.390017,0.401991,0.326229,0.378412,0.393584,0.298625
3,0.838025,0.830188,0.873322,0.852851,0.851817,0.891550,0.867510,0.872817,0.906731,0.866459,...,0.817786,0.727923,0.759296,0.809675,0.714688,0.746061,0.796440,0.720473,0.751846,0.802225
4,0.625681,0.668134,0.675978,0.566850,0.606086,0.613940,0.538995,0.573577,0.583737,0.540187,...,0.478007,0.745488,0.510689,0.471016,0.717843,0.487477,0.446101,0.669600,0.452027,0.428233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,0.169945,0.154726,0.144652,0.178765,0.163114,0.158764,0.227005,0.210713,0.215206,0.255978,...,0.194028,0.672700,0.667209,0.264269,0.897179,0.914992,0.311070,0.905768,0.928008,0.244797
122,0.848785,0.825256,0.778197,0.853138,0.829609,0.782550,0.859961,0.836432,0.789373,0.864315,...,0.843427,0.914581,0.901095,0.886225,0.891244,0.865340,0.767687,0.843795,0.821282,0.704931
123,0.661561,0.649084,0.689929,0.678733,0.669130,0.702080,0.622789,0.623406,0.643414,0.652441,...,0.202541,0.310077,0.301230,0.180257,0.216560,0.248620,0.111527,0.251654,0.281901,0.122102
124,0.207515,0.226768,0.016067,0.211554,0.231162,0.019397,0.218255,0.237862,0.025959,0.221726,...,0.751973,0.922093,0.840891,0.725256,0.904268,0.787756,0.676284,0.905882,0.784314,0.674510
125,0.076956,0.131472,0.080685,0.081602,0.124973,0.079574,0.072546,0.098939,0.063017,0.078754,...,0.295455,0.221415,0.253037,0.304177,0.221985,0.253452,0.304644,0.223262,0.254541,0.305828

In [ ]:
df["target"]=target_arr
df

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,target
0,0.450773,0.011956,0.071498,0.450767,0.006846,0.059286,0.471130,0.015850,0.064732,0.474026,...,0.642030,0.015206,0.069585,0.646300,0.015762,0.079527,0.654410,0.026855,0.074540,0
1,0.266514,0.270436,0.278279,0.281895,0.285817,0.293660,0.320151,0.324072,0.331915,0.285575,...,0.701904,0.736721,0.795792,0.687784,0.732520,0.788196,0.676392,0.726043,0.779649,0
2,0.364724,0.310068,0.119902,0.385498,0.332242,0.135228,0.405248,0.354222,0.147759,0.422624,...,0.400584,0.412349,0.337839,0.390017,0.401991,0.326229,0.378412,0.393584,0.298625,0
3,0.838025,0.830188,0.873322,0.852851,0.851817,0.891550,0.867510,0.872817,0.906731,0.866459,...,0.727923,0.759296,0.809675,0.714688,0.746061,0.796440,0.720473,0.751846,0.802225,0
4,0.625681,0.668134,0.675978,0.566850,0.606086,0.613940,0.538995,0.573577,0.583737,0.540187,...,0.745488,0.510689,0.471016,0.717843,0.487477,0.446101,0.669600,0.452027,0.428233,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,0.169945,0.154726,0.144652,0.178765,0.163114,0.158764,0.227005,0.210713,0.215206,0.255978,...,0.672700,0.667209,0.264269,0.897179,0.914992,0.311070,0.905768,0.928008,0.244797,1
122,0.848785,0.825256,0.778197,0.853138,0.829609,0.782550,0.859961,0.836432,0.789373,0.864315,...,0.914581,0.901095,0.886225,0.891244,0.865340,0.767687,0.843795,0.821282,0.704931,1
123,0.661561,0.649084,0.689929,0.678733,0.669130,0.702080,0.622789,0.623406,0.643414,0.652441,...,0.310077,0.301230,0.180257,0.216560,0.248620,0.111527,0.251654,0.281901,0.122102,1
124,0.207515,0.226768,0.016067,0.211554,0.231162,0.019397,0.218255,0.237862,0.025959,0.221726,...,0.922093,0.840891,0.725256,0.904268,0.787756,0.676284,0.905882,0.784314,0.674510,1
125,0.076956,0.131472,0.080685,0.081602,0.124973,0.079574,0.072546,0.098939,0.063017,0.078754,...,0.221415,0.253037,0.304177,0.221985,0.253452,0.304644,0.223262,0.254541,0.305828,1

In [ ]:
x=df.iloc[:,:-2]
x

,0,1,2,3,4,5,6,7,8,9,...,67489,67490,67491,67492,67493,67494,67495,67496,67497,67498
0,0.450773,0.011956,0.071498,0.450767,0.006846,0.059286,0.471130,0.015850,0.064732,0.474026,...,0.027718,0.062624,0.642030,0.015206,0.069585,0.646300,0.015762,0.079527,0.654410,0.026855
1,0.266514,0.270436,0.278279,0.281895,0.285817,0.293660,0.320151,0.324072,0.331915,0.285575,...,0.740082,0.802532,0.701904,0.736721,0.795792,0.687784,0.732520,0.788196,0.676392,0.726043
2,0.364724,0.310068,0.119902,0.385498,0.332242,0.135228,0.405248,0.354222,0.147759,0.422624,...,0.418936,0.344426,0.400584,0.412349,0.337839,0.390017,0.401991,0.326229,0.378412,0.393584
3,0.838025,0.830188,0.873322,0.852851,0.851817,0.891550,0.867510,0.872817,0.906731,0.866459,...,0.767407,0.817786,0.727923,0.759296,0.809675,0.714688,0.746061,0.796440,0.720473,0.751846
4,0.625681,0.668134,0.675978,0.566850,0.606086,0.613940,0.538995,0.573577,0.583737,0.540187,...,0.515300,0.478007,0.745488,0.510689,0.471016,0.717843,0.487477,0.446101,0.669600,0.452027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,0.169945,0.154726,0.144652,0.178765,0.163114,0.158764,0.227005,0.210713,0.215206,0.255978,...,0.387565,0.194028,0.672700,0.667209,0.264269,0.897179,0.914992,0.311070,0.905768,0.928008
122,0.848785,0.825256,0.778197,0.853138,0.829609,0.782550,0.859961,0.836432,0.789373,0.864315,...,0.854422,0.843427,0.914581,0.901095,0.886225,0.891244,0.865340,0.767687,0.843795,0.821282
123,0.661561,0.649084,0.689929,0.678733,0.669130,0.702080,0.622789,0.623406,0.643414,0.652441,...,0.298643,0.202541,0.310077,0.301230,0.180257,0.216560,0.248620,0.111527,0.251654,0.281901
124,0.207515,0.226768,0.016067,0.211554,0.231162,0.019397,0.218255,0.237862,0.025959,0.221726,...,0.839730,0.751973,0.922093,0.840891,0.725256,0.904268,0.787756,0.676284,0.905882,0.784314
125,0.076956,0.131472,0.080685,0.081602,0.124973,0.079574,0.072546,0.098939,0.063017,0.078754,...,0.244371,0.295455,0.221415,0.253037,0.304177,0.221985,0.253452,0.304644,0.223262,0.254541

In [ ]:
y=df.iloc[:,-2]
y

0      0.074540
1      0.779649
2      0.298625
3      0.802225
4      0.428233
         ...
121    0.244797
122    0.704931
123    0.122102
124    0.674510
125    0.305828
Name: 67499, Length: 126, dtype: float64

In [ ]:
df.isna().sum()

0         0
1         0
2         0
3         0
4         0
         ..
67496     0
67497     0
67498     0
67499     0
target    0
Length: 67501, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=6)

In [ ]:
from sklearn.svm import SVC
sv=SVC()#(kernel="linear")
sv.fit(x_train,y_train)
ypred=sv.predict(x_test)
ypred

ValueError: ignored

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,ConfusionMatrixDisplay
print(accuracy_score(y_test,ypred))

In [ ]:
print(ConfusionMatrixDisplay.from_predictions(y_test,ypred))